forge "http://forge.puppetlabs.com"

mod "apt",
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "stdlib",
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod "puppi",
  :git => "git://github.com/example42/puppi.git"

mod "nginx",
  :git => "git://github.com/netmanagers/puppet-nginx.git"

 mod "mysql",
  :git => "git://github.com/example42/puppet-mysql.git"
